### ISSUE TITLE
New columns to be displayed - based on check boxes

### ISSUE THREAD

**Issue by wizard-31** [sak007/expertiza#7]
We would like to have the following columns potentially shown, depending on whether the corresponding box is checked
i) Instructor-assigned scores
ii) Peer grades
iii) Teammate review scores 
iv) Topics
v) Meta-review scores (only show if the set of deadlines has a meta-review deadline). find_due_dates(metareview) see the deadline_types table for the parameter name
vi) Number of teammates [cumulative]

**Comment by wizard-31** [comment]
Fixed in commit - 2307da74948b10b1579951a41d4f1b133df1f9f2

**Comment by sak1997** [comment]
Verified and tested - looks good.

**Comment by wizard-31** [comment]
All fixes done and merged with beta branch - b0cefcf708e9959c626287cbd2ed9090c27e48e6 PR #14
